import { LocaleConfig } from '@/locales/types';

interface PageSEO {
  getTitle: (locale: LocaleConfig) => string;
  getDescription: (locale: LocaleConfig) => string;
  ogType: 'website' | 'article';
  priority: number;
  changefreq: 'daily' | 'weekly' | 'monthly';
}

export const pageSEO: Record<string, PageSEO> = {
  '/': {
    getTitle: (locale) => `Invoicemonk — Invoicing & Accounting Software for ${locale.content.seo.targetAudience} Businesses`,
    getDescription: (locale) => `Professional invoicing, expense tracking, and accounting in one platform. ${locale.content.seo.complianceKeyword} for ${locale.content.seo.region}. Free tier available — no credit card required.`,
    ogType: 'website',
    priority: 1.0,
    changefreq: 'weekly',
  },
  '/invoicing': {
    getTitle: (locale) => `Free Invoicing Software for Small Business — Create Invoices in 2 Minutes | Invoicemonk`,
    getDescription: (locale) => `The easiest invoicing software for freelancers and small businesses in ${locale.content.seo.region}. Professional templates, automatic reminders, multi-currency — free to start.`,
    ogType: 'website',
    priority: 0.9,
    changefreq: 'weekly',
  },
  '/pricing': {
    getTitle: (locale) => `Pricing | Invoicemonk ${locale.content.seo.region}`,
    getDescription: (locale) => `Invoicemonk pricing for ${locale.content.seo.region}. Pro plan from $29/mo. Free tier available.`,
    ogType: 'website',
    priority: 0.9,
    changefreq: 'weekly',
  },
  '/expenses': {
    getTitle: (locale) => `Best Receipt Scanning & Expense Tracking App for Small Business 2026 | Invoicemonk`,
    getDescription: (locale) => `Receipt scanning with AI-powered OCR, automatic expense categorization, and tax-ready reports. Stay ${locale.content.seo.complianceKeyword.toLowerCase()} and save 5+ hours/month on bookkeeping.`,
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/payments': {
    getTitle: (locale) => `Accept Online Payments for ${locale.content.seo.targetAudience} Businesses | Invoicemonk`,
    getDescription: (locale) => `Get paid faster with ${locale.content.paymentGateway} integration. Accept online payments directly from your invoices. Built for ${locale.content.seo.region}.`,
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/accounting': {
    getTitle: (locale) => `${locale.content.seo.complianceKeyword} Accounting Software | Invoicemonk`,
    getDescription: (locale) => `Simple accounting software for ${locale.content.seo.targetAudience} small businesses. Track income, expenses, and stay tax-ready.`,
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/estimates': {
    getTitle: (locale) => `Create Professional Estimates & Quotes | Invoicemonk ${locale.content.seo.region}`,
    getDescription: (locale) => `Send professional estimates and quotes to win more clients. Convert to invoices with one click. Built for ${locale.content.seo.targetAudience} businesses.`,
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/receipts': {
    getTitle: (locale) => `Best Receipt Scanning App 2026 — AI-Powered Digital Receipt Management | Invoicemonk`,
    getDescription: (locale) => `Scan, organize, and store receipts digitally with AI-powered OCR. Instant search, tax-ready exports, and secure cloud storage for ${locale.content.seo.targetAudience} businesses.`,
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/compliance': {
    getTitle: (locale) => `${locale.content.compliance.authority} Tax Compliance | Invoicemonk`,
    getDescription: (locale) => `${locale.content.compliance.message}. Stay audit-ready with automatic tax calculations and reports.`,
    ogType: 'website',
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/freelancers': {
    getTitle: () => `Best Freelance Invoice Software 2026 — Free for Freelancers | Invoicemonk`,
    getDescription: (locale) => `Create professional freelance invoices in under 2 minutes. Automatic payment reminders, multi-currency, and income tracking in ${locale.content.seo.region} — 100% free to start.`,
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/small-businesses': {
    getTitle: (locale) => `Invoicing Software for ${locale.content.seo.targetAudience} Small Businesses | Invoicemonk`,
    getDescription: (locale) => `Complete invoicing and accounting solution for small businesses in ${locale.content.seo.region}. Free tier available.`,
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/blog': {
    getTitle: (locale) => `Business & Finance Blog | Invoicemonk ${locale.content.seo.region}`,
    getDescription: (locale) => `Tips, guides, and insights for ${locale.content.seo.targetAudience} small businesses and freelancers. Learn invoicing, accounting, and business growth strategies.`,
    ogType: 'website',
    priority: 0.7,
    changefreq: 'daily',
  },
  '/about': {
    getTitle: () => 'About Invoicemonk | Our Story & Mission',
    getDescription: () => 'Learn about Invoicemonk - the invoicing and accounting platform built for businesses worldwide. Our mission is to simplify financial management.',
    ogType: 'website',
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/contact': {
    getTitle: (locale) => `Contact Invoicemonk ${locale.content.seo.region} | Get Support`,
    getDescription: (locale) => `Get in touch with Invoicemonk. We're here to help ${locale.content.seo.targetAudience} businesses with invoicing and accounting needs.`,
    ogType: 'website',
    priority: 0.5,
    changefreq: 'monthly',
  },
  '/privacy-policy': {
    getTitle: () => 'Privacy Policy | Invoicemonk',
    getDescription: () => 'Learn how Invoicemonk protects your data and respects your privacy. Our comprehensive privacy policy explains our data practices.',
    ogType: 'website',
    priority: 0.3,
    changefreq: 'monthly',
  },
  '/terms-of-service': {
    getTitle: () => 'Terms of Service | Invoicemonk',
    getDescription: () => 'Read the Invoicemonk terms of service. Understand your rights and responsibilities when using our invoicing platform.',
    ogType: 'website',
    priority: 0.3,
    changefreq: 'monthly',
  },
  '/why-invoicemonk': {
    getTitle: (locale) => `Why Choose Invoicemonk | ${locale.content.seo.complianceKeyword} Invoicing`,
    getDescription: (locale) => `Discover why ${locale.content.seo.targetAudience} businesses choose Invoicemonk. ${locale.content.seo.complianceKeyword} invoicing, powerful features, and excellent support.`,
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/developer': {
    getTitle: () => 'Developer API | Invoicemonk',
    getDescription: () => 'Integrate Invoicemonk into your applications with our developer API. Full documentation and SDKs available.',
    ogType: 'website',
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/client-management': {
    getTitle: (locale) => `Client Management for ${locale.content.seo.targetAudience} Businesses | Invoicemonk`,
    getDescription: (locale) => `Manage client information, track payment history, and build better relationships. Built for ${locale.content.seo.region} businesses.`,
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/glossary': {
    getTitle: () => 'Business Finance Glossary | Invoicing & Accounting Terms | Invoicemonk',
    getDescription: () => 'Comprehensive glossary of invoicing, payments, accounting, tax, and business finance terms. Learn key concepts for small business owners and freelancers.',
    ogType: 'website',
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/consultants': {
    getTitle: () => 'Invoicing Software for Consultants | Invoicemonk',
    getDescription: () => 'Professional invoicing for management consultants and strategy firms. Multi-currency billing, detailed reporting, and enterprise-ready compliance.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/contractors': {
    getTitle: () => 'Invoicing Software for Contractors | Invoicemonk',
    getDescription: () => 'Professional invoicing built for electrical, building, and trade contractors. Mobile invoicing, multi-project tracking, and job expense management.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/cookie-policy': {
    getTitle: () => 'Cookie Policy | Invoicemonk',
    getDescription: () => 'Learn how Invoicemonk uses cookies and similar technologies. Manage your cookie preferences and understand your choices.',
    ogType: 'website',
    priority: 0.3,
    changefreq: 'monthly',
  },
  '/guides': {
    getTitle: () => 'Business Guides & Resources | Invoicemonk',
    getDescription: () => 'Comprehensive guides on invoicing, getting paid, accounting, tax compliance, freelancing, and business proposals.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/explore': {
    getTitle: () => 'Explore Topics & Reviews | Invoicemonk',
    getDescription: () => 'Explore our comprehensive topic guides, read customer reviews, and track your learning progress.',
    ogType: 'website',
    priority: 0.6,
    changefreq: 'weekly',
  },
  '/international-payment-fee-calculator': {
    getTitle: () => 'International Payment Fee Calculator 2026 — Compare Wise, PayPal & Bank Fees',
    getDescription: () => 'Enter an amount and see exactly what you\'ll receive after fees. Compare Wise vs PayPal vs SWIFT vs card payments side by side — free calculator, updated March 2026.',
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/paypal-vs-wise-fees': {
    getTitle: () => 'Wise vs PayPal Fees: Real Cost on $500, $1K & $5K Transfers (2026)',
    getDescription: () => 'We sent $500, $1,000 & $5,000 through Wise and PayPal and tracked every fee. Wise saved 3–6x on average. See the full breakdown with screenshots.',
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/cheapest-way-to-receive-international-payments': {
    getTitle: () => 'Cheapest Way to Receive International Payments — Ranked by Real Cost (2026)',
    getDescription: () => 'We ranked Wise, PayPal, SWIFT, Payoneer & card payments by total cost on real transfers. Use our free calculator to find the cheapest option for your corridor.',
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
  '/agencies': {
    getTitle: () => 'Invoicing Software for Agencies | Invoicemonk',
    getDescription: () => 'Streamline agency billing with retainer invoicing, multi-project tracking, and branded invoices. Built for digital, creative, and marketing agencies.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/photographers': {
    getTitle: () => 'Invoice Software for Photographers | Invoicemonk',
    getDescription: () => 'Create professional photography invoices with milestone payments, package billing, and branded templates. Perfect for wedding, event, and commercial photographers.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/lawyers': {
    getTitle: () => 'Legal Billing Software for Lawyers | Invoicemonk',
    getDescription: () => 'Professional legal billing with time tracking, retainer management, and detailed invoicing. Built for law firms, solo practitioners, and legal consultants.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/accountants': {
    getTitle: () => 'Invoicing for Accountants & Bookkeepers | Invoicemonk',
    getDescription: () => 'Multi-client invoicing and billing for accountants, bookkeepers, and accounting firms. Recurring billing, tax compliance, and detailed financial reporting.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/ecommerce': {
    getTitle: () => 'Invoicing for E-commerce Sellers | Invoicemonk',
    getDescription: () => 'Professional invoicing for e-commerce businesses. B2B wholesale billing, multi-currency invoicing, and subscription billing for online sellers.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/creatives': {
    getTitle: () => 'Invoicing for Creatives & Designers | Invoicemonk',
    getDescription: () => 'Professional invoicing for graphic designers, illustrators, videographers, and creative freelancers. Project billing, branded invoices, and payment tracking.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/compare/invoicemonk-vs-freshbooks': {
    getTitle: () => 'Invoicemonk vs FreshBooks: Which Is Better? | 2026 Comparison',
    getDescription: () => 'Compare Invoicemonk and FreshBooks side by side. Features, pricing, and which invoicing software is best for your business.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/compare/invoicemonk-vs-wave': {
    getTitle: () => 'Invoicemonk vs Wave: Which Free Invoicing Software Is Better? | 2026',
    getDescription: () => 'Compare Invoicemonk and Wave side by side. Both offer free invoicing, but differ in currency support, global availability, and features.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/compare/invoicemonk-vs-zoho-invoice': {
    getTitle: () => 'Invoicemonk vs Zoho Invoice: Simpler Alternative | 2026 Comparison',
    getDescription: () => 'Compare Invoicemonk and Zoho Invoice. See how features, pricing, and ease of use stack up for small businesses.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/compare/invoicemonk-vs-quickbooks': {
    getTitle: () => 'Invoicemonk vs QuickBooks: Affordable Alternative | 2026 Comparison',
    getDescription: () => 'Compare Invoicemonk and QuickBooks for small business invoicing. See features, pricing, and which is the best fit.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/compare/invoicemonk-vs-atoinvoice': {
    getTitle: () => 'Better Than Atoinvoice? Free GST Invoice Generator with CGST/SGST/IGST (2026)',
    getDescription: () => 'Looking for an Atoinvoice alternative? Invoicemonk offers free GST invoicing with CGST, SGST & IGST — plus multi-currency, UPI payments, and no signup. Compare now.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/best-invoicing-software': {
    getTitle: () => '7 Best Invoicing Software 2026 — Tested for 30 Days Each (Honest Review)',
    getDescription: () => 'I tested Invoicemonk, FreshBooks, Wave, Zoho & QuickBooks for 30 days each. Full comparison table, pricing, pros, cons — and which one I actually use.',
    ogType: 'website',
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/use-cases/recurring-billing': {
    getTitle: () => 'Recurring Invoices & Subscription Billing — Set Up in 5 Minutes | Invoicemonk',
    getDescription: () => 'Automate recurring invoices for retainers, subscriptions, and monthly clients. Set it once, get paid on schedule — no manual work.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/use-cases/multi-currency-invoicing': {
    getTitle: () => 'Multi-Currency Invoicing — Invoice Clients in Any Currency | Invoicemonk',
    getDescription: () => 'Send invoices in USD, EUR, GBP, or any of 150+ currencies. Automatic conversion, localized formatting, and no per-currency fees.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/use-cases/milestone-billing': {
    getTitle: () => 'Milestone Billing & Progress Invoicing | Invoicemonk',
    getDescription: () => 'Bill clients at project milestones with deposit, progress, and final invoices. Perfect for photographers, developers, and project-based businesses.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/help': {
    getTitle: () => 'Help Center | Invoicemonk Support',
    getDescription: () => 'Get help with Invoicemonk. Browse guides on invoicing, payments, expenses, accounting, and more. Find answers to common questions.',
    ogType: 'website',
    priority: 0.6,
    changefreq: 'weekly',
  },
  '/use-cases/retainer-billing': {
    getTitle: () => 'Retainer Billing & Client Retainer Invoicing | Invoicemonk',
    getDescription: () => 'Automate retainer invoicing for ongoing client relationships. Recurring billing, drawdown tracking, and professional retainer management.',
    ogType: 'website',
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/docs/api': {
    getTitle: () => 'API Documentation | Invoicemonk',
    getDescription: () => 'Full API reference for the Invoicemonk compliance infrastructure. Endpoints, authentication, audit logging, rate limiting, and security.',
    ogType: 'website',
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/legal/sla': {
    getTitle: () => 'Service Level Agreement (SLA) | Invoicemonk',
    getDescription: () => 'Service commitments, availability targets, data integrity guarantees, and security controls for the Invoicemonk platform.',
    ogType: 'website',
    priority: 0.3,
    changefreq: 'monthly',
  },
  '/invoice-templates': {
    getTitle: () => 'Free Invoice Templates 2026 — Download & Customize PDF Templates | Invoicemonk',
    getDescription: () => 'Browse 6 professional invoice templates for freelancers, contractors, consultants, and small businesses. Customize with your logo, download as PDF — 100% free.',
    ogType: 'website',
    priority: 0.9,
    changefreq: 'weekly',
  },
  '/freelancer-rate-calculator': {
    getTitle: () => 'Freelancer Rate Calculator 2026 — Find Your Ideal Hourly Rate | Invoicemonk',
    getDescription: () => 'Calculate your freelance hourly rate based on income goals, expenses, taxes, and billable hours. Free interactive calculator — no signup required.',
    ogType: 'website',
    priority: 0.8,
    changefreq: 'weekly',
  },
};

export const getPageSEO = (path: string): PageSEO | undefined => {
  return pageSEO[path];
};
