/**
 * Content audit: ranks every blog article by depth + LLM-readiness.
 *
 * Emits docs/content-audit.md with word count, H2 count, table/FAQ/
 * direct-answer presence, cluster file and a verdict:
 *   expand | merge | prune | keep
 *
 * Run: bunx tsx scripts/content-audit.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DATA_DIR = path.join(__dirname, '../src/data');
const OUT = path.join(__dirname, '../docs/content-audit.md');

const THIN = 900;

/** Off-topic legacy posts with no commercial fit for an invoicing product. */
const PRUNE = new Set([
  'impact-of-fintech-on-business-growth',
  'savings-and-investment-on-alat-how-it-works',
  'how-to-become-a-good-graphic-designer',
  'top-10-freelance-websites',
  'top-10-lucrative-business-ideas-with-small-capital',
  'small-business-marketing-101-a-guide-to-growth',
]);

/** Country-mandate spin-offs: merge into the country hub rather than pad. */
const MANDATE_PREFIXES = [
  'nigeria-', 'kenya-', 'ghana-', 'romania-', 'colombia-', 'hungary-',
  'mexico-', 'spain-', 'italy-', 'brazil-', 'chile-', 'poland-',
  'bulgaria-', 'malaysia-', 'saudi-', 'germany-', 'france-', 'india-',
  'philippines-', 'zimbabwe-', 'seychelles-', 'south-africa-', 'belgium-',
];

export interface AuditRow {
  slug: string;
  file: string;
  words: number;
  h2: number;
  table: boolean;
  faq: boolean;
  answer: boolean;
  usFacing: boolean;
  verdict: 'expand' | 'merge' | 'prune' | 'keep';
}

function isMandate(slug: string) {
  return MANDATE_PREFIXES.some((p) => slug.startsWith(p)) ||
    /e-invoicing|peppol|ksef|zatca|myinvois|etims|fatturapa|cfdi|verifactu|xrechnung|zugferd/.test(slug);
}

export function auditAll(): AuditRow[] {
  const files = fs.readdirSync(DATA_DIR).filter((f) => /^blogPosts.*\.ts$/.test(f));
  const rows: AuditRow[] = [];

  for (const file of files) {
    const src = fs.readFileSync(path.join(DATA_DIR, file), 'utf-8');
    const re = /slug:\s*['"`]([^'"`]+)['"`]/g;
    const marks: Array<[number, string]> = [];
    let m: RegExpExecArray | null;
    while ((m = re.exec(src)) !== null) marks.push([m.index, m[1]]);

    for (let i = 0; i < marks.length; i++) {
      const seg = src.slice(marks[i][0], i + 1 < marks.length ? marks[i + 1][0] : src.length);
      const slug = marks[i][1];
      const words = seg.replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length;
      const h2 = (seg.match(/<h2/g) || []).length;
      const table = /<table/.test(seg);
      const faq = /frequently asked questions|faq/i.test(seg);
      const answer = /data-answer/.test(seg);
      const usFacing = !isMandate(slug) && !PRUNE.has(slug);

      let verdict: AuditRow['verdict'];
      if (PRUNE.has(slug)) verdict = 'prune';
      else if (words < THIN && isMandate(slug)) verdict = 'merge';
      else if (words < THIN || !answer || (!faq && !table)) verdict = 'expand';
      else verdict = 'keep';

      rows.push({ slug, file, words, h2, table, faq, answer, usFacing, verdict });
    }
  }

  // Worst-first, US-facing pages ahead of mandate pages at equal depth.
  rows.sort((a, b) => Number(b.usFacing) - Number(a.usFacing) || a.words - b.words);
  return rows;
}

function yn(v: boolean) {
  return v ? 'yes' : 'no';
}

function section(title: string, rows: AuditRow[]) {
  if (rows.length === 0) return '';
  const head = '| Slug | Words | H2 | Table | FAQ | Answer block | File |\n|---|---|---|---|---|---|---|\n';
  const body = rows
    .map((r) => `| ${r.slug} | ${r.words} | ${r.h2} | ${yn(r.table)} | ${yn(r.faq)} | ${yn(r.answer)} | ${r.file} |`)
    .join('\n');
  return `\n## ${title} (${rows.length})\n\n${head}${body}\n`;
}

function main() {
  const rows = auditAll();
  const counts = {
    total: rows.length,
    thin: rows.filter((r) => r.words < THIN).length,
    noAnswer: rows.filter((r) => !r.answer).length,
    noTable: rows.filter((r) => !r.table).length,
    noFaq: rows.filter((r) => !r.faq).length,
  };

  const md = [
    '# Content audit',
    '',
    `Generated by \`scripts/content-audit.ts\`. Articles: **${counts.total}**.`,
    '',
    `- Under ${THIN} words: **${counts.thin}**`,
    `- No direct-answer block: **${counts.noAnswer}**`,
    `- No table: **${counts.noTable}**`,
    `- No FAQ: **${counts.noFaq}**`,
    '',
    'Verdicts: **prune** = off-topic legacy, **merge** = thin mandate spin-off that belongs in its country hub, **expand** = needs depth or LLM structure, **keep** = already answer-shaped.',
    section('Prune', rows.filter((r) => r.verdict === 'prune')),
    section('Expand — US-facing (priority)', rows.filter((r) => r.verdict === 'expand' && r.usFacing)),
    section('Merge — thin mandate spin-offs', rows.filter((r) => r.verdict === 'merge')),
    section('Expand — non-US', rows.filter((r) => r.verdict === 'expand' && !r.usFacing)),
    section('Keep', rows.filter((r) => r.verdict === 'keep')),
  ].join('\n');

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, md);
  console.log(`Wrote ${OUT}`);
  console.table(counts);
  for (const v of ['prune', 'merge', 'expand', 'keep'] as const) {
    console.log(v, rows.filter((r) => r.verdict === v).length);
  }
}

main();
