/**
 * Route inventory for the build-time prerenderer.
 *
 * public/sitemap.xml is generated by a regex scan of the data files, so it
 * misses posts that are produced programmatically (e.g. the country
 * compliance posts in src/data/countryCompliancePosts.ts). Those pages were
 * exactly the ones Google reported as duplicates, so the prerenderer reads
 * the live in-memory registries here instead of trusting the sitemap alone.
 */

// Side-effect imports: register every cluster post into the blogPosts array.
import '@/data/blogPostsCluster9';
import '@/data/blogPostsCluster10';
import '@/data/blogPostsCluster11';
import '@/data/blogPostsCluster12';
import '@/data/blogPostsCluster13';
import '@/data/blogPostsCluster14';
import '@/data/blogPostsCluster15';
import '@/data/blogPostsCluster16';
import '@/data/blogPostsCluster17';
import '@/data/blogPostsCluster18';
import '@/data/blogPostsCluster19';
import '@/data/blogPostsCluster20';
import '@/data/blogPostsCluster21';
import '@/data/blogPostsCluster22';
import '@/data/blogPostsClusterEInvoicing';
import '@/data/blogPostsClusterEInvoicing2';
import '@/data/blogPostsClusterEInvoicing3';
import '@/data/blogPostsClusterEInvoicing4';
import '@/data/blogPostsClusterEInvoicing5';
import '@/data/blogPostsClusterEInvoicing6';
import '@/data/blogPostsClusterEInvoicingItalyBulgaria';

import { blogPosts } from '@/data/blogPosts';
import { helpGuides } from '@/data/helpGuides';
import { authors } from '@/data/authors';
import { mandates } from '@/data/mandates';
import { pillars } from '@/data/topicalMap';

const LANG = 'en';

/**
 * Real pages that exist as routes in App.tsx but are absent from the
 * generated sitemap, so the prerenderer would otherwise skip them and the
 * SPA fallback would serve them the noindex 404 shell.
 */
const EXTRA_STATIC_ROUTES = ['partner-program', 'tools'];

export function getContentRoutes(): string[] {
  const routes = new Set<string>();

  for (const route of EXTRA_STATIC_ROUTES) {
    routes.add(`/${LANG}/${route}`);
  }

  for (const post of blogPosts) {
    if (post?.slug) routes.add(`/${LANG}/blog/${post.slug}`);
  }
  for (const guide of helpGuides) {
    if (guide?.slug) routes.add(`/${LANG}/help/${guide.slug}`);
  }
  for (const slug of Object.keys(authors)) {
    routes.add(`/${LANG}/blog/author/${slug}`);
  }
  for (const mandate of mandates) {
    if (mandate?.slug) routes.add(`/${LANG}/e-invoicing/${mandate.slug}`);
  }
  for (const pillar of pillars) {
    if (pillar?.slug) routes.add(`/${LANG}/guides/${pillar.slug}`);
  }

  return [...routes];
}
